services:
  sad_vio:
    build:
      context: .
      dockerfile: Dockerfile
    image: sad_vio:latest
    container_name: sad_vio_dense
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY:-:1}
      - QT_X11_NO_MITSHM=1
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - ~/EXECO/Simulator_Validation:/Simulator_Validation
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
