#!/usr/bin/env python3
"""Collect the metrics of every run under runs/ into one CSV and one per-cell summary.

Runs without metrics.json are evaluated first (eval_traj.evaluate). Writes
  all_runs_metrics.csv   one row per run (label, seq, mode, run, overrides, metrics)
  RESULTS_ALL_RUNS.md    mean ± std per (label, seq, mode)
next to tools/. RPE: translation over 1 s and 5 s, rotation over 1 s (TUM-VI); for the RealSense sequences the
translation RPE is in the aligned world frame and there is no rotation RPE (uncalibrated GT body).
"""
import csv, json, sys
from collections import defaultdict
from pathlib import Path
import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from eval_traj import evaluate  # noqa: E402

EVAL = HERE.parent
KEYS = ['ate_rmse', 'rpe_t_1s', 'rpe_t_5s', 'rpe_r_1s_deg', 'scale', 'end_drift', 'coverage', 'resets', 'crashed',
        'wall_s']

rows = []
for rj in sorted((EVAL / 'runs').glob('*/*/*/run_*/run.json')):
    rd = rj.parent
    mf = rd / 'metrics.json'
    try:
        m = json.loads(mf.read_text()) if mf.exists() else evaluate(rd)
    except Exception as e:  # unreadable or empty run
        m = {'error': str(e)}
    meta = json.loads(rj.read_text())
    label, seq, mode = rd.parts[-4], rd.parts[-3], rd.parts[-2]
    ov = ' '.join(f'{k}={v}' for k, v in sorted(meta.get('overrides', {}).items()))
    rows.append(dict(label=label, seq=seq, mode=mode, run=rd.name, overrides=ov,
                     **{k: m.get(k) for k in KEYS}))

with open(EVAL / 'all_runs_metrics.csv', 'w', newline='') as f:
    w = csv.DictWriter(f, fieldnames=['label', 'seq', 'mode', 'run', 'overrides'] + KEYS)
    w.writeheader()
    w.writerows(rows)

cells = defaultdict(list)
for r in rows:
    cells[(r['label'], r['seq'], r['mode'], r['overrides'])].append(r)


def fmt(vals, d=3):
    v = [x for x in vals if x is not None]
    if not v:
        return '—'
    return f'{np.mean(v):.{d}f}' + (f' ± {np.std(v):.{d}f}' if len(v) > 1 else '')


lines = ['# All runs — metrics per cell (mean ± std over runs)', '',
         'Generated by `tools/collect_metrics.py` from `runs/*/*/*/run_*/metrics.json` (per-run values:',
         '`all_runs_metrics.csv`). ATE: RMSE after SE3 (stereo) / Sim3 (mono) Umeyama alignment, cross-checked',
         'against evo_ape (≤ 1 mm difference). RPE: translation error over 1 s and 5 s pairs, rotation over 1 s;',
         'RealSense (`rs_*`): translation RPE in the aligned world frame, no rotation RPE. Mono VO ATE covers only',
         'the segment after its last re-initialization (see coverage).', '',
         '| label | seq | mode | overrides | n | ATE (m) | RPE 1 s (m) | RPE 5 s (m) | RPE rot 1 s (°) | scale | coverage | resets |',
         '|---|---|---|---|---|---|---|---|---|---|---|---|']
for (label, seq, mode, ov), rs in sorted(cells.items()):
    lines.append(f"| {label} | {seq} | {mode} | {ov or 'default'} | {len(rs)} | {fmt([r['ate_rmse'] for r in rs])} | "
                 f"{fmt([r['rpe_t_1s'] for r in rs])} | {fmt([r['rpe_t_5s'] for r in rs])} | "
                 f"{fmt([r['rpe_r_1s_deg'] for r in rs], 2)} | {fmt([r['scale'] for r in rs])} | "
                 f"{fmt([r['coverage'] for r in rs], 2)} | {sum((r['resets'] or 0) for r in rs)} |")
(EVAL / 'RESULTS_ALL_RUNS.md').write_text('\n'.join(lines) + '\n')
print(f'{len(rows)} runs, {len(cells)} cells -> all_runs_metrics.csv, RESULTS_ALL_RUNS.md')
